import CreateForm from './CreateForm';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create New Study Session',
	description: 'Generated by create next app',
};

export default function Create() {
	return (
		<main className="Create container">
			<h2 className="text-primary text-center">Add a New Study Session</h2>
			<CreateForm />
		</main>
	);
}
